### ISSUE TITLE
"reason": "Custom Analyzer [minhash_analyzer] failed to find filter under name [minhash]"

### ISSUE THREAD

**Issue by Cheney550995353** [codelibs/elasticsearch-minhash#12]
按照readme操作，安装好minhash插件后，

curl -XPUT 'localhost:9200/my_index' -d '{
  "index":{
    "analysis":{
      "analyzer":{
        "minhash_analyzer":{
          "type":"custom",
          "tokenizer":"standard",
          "filter":["minhash"]
        }
      }
    }
  }
}'
报错误
"type": "illegal_argument_exception",
"reason": "Custom Analyzer [minhash_analyzer] failed to find filter under name [minhash]"

**Comment by marevol** [comment]
Please use English...
