### ISSUE TITLE
How to use copy_bits_to operator?

### ISSUE THREAD

**Issue by Fred12** [codelibs/elasticsearch-minhash#19]
I was using minhash plugin with kibana, but I couldnt retrieve the bits keyword field in GET...

PUT /test_minhash_test
{
"index":{
"analysis":{
"analyzer":{
"minhash_analyzer":{
"type":"custom",
"tokenizer":"standard",
"filter":["minhash"]
}
}
}
}
}

PUT /test_minhash_test/_doc/_mapping
{
"_doc":{
"properties":{
"message": {
"type":"text",
"copy_to":"minhash_value"
},
"minhash_value":{
"type":"minhash",
"minhash_analyzer":"minhash_analyzer",
"store":true,
"copy_bits_to": "content_minhash_bits"
},
"content_minhash_bits": {
"type": "keyword",
"store":true
}
}
}
}

GET /test_minhash_test/_doc/_search/?pretty&stored_fields=*

What am I doing wrong?

**Comment by Fred12** [comment]
here is my fess.log:
[fess.log](https://github.com/codelibs/elasticsearch-minhash/files/2977980/fess.log)

**Comment by Fred12** [comment]
any ideas how to retrieve the content_minhash_bits field? I am stuck in getting the field ? What am I doing wrong?

**Comment by karlkovaciny** [comment]
I guess this issue can be closed since copy_bits_to was [removed in 2021](https://github.com/codelibs/elasticsearch-minhash/commit/1c8c337c0de7793d5a6844e23cf61d472d4a6de5) (don't know why).

**Comment by marevol** [comment]
Elasticsearch often changes their interfaces, so it's difficult to keep the copy_bits_to setting.
